version: "3.9"

services:
  aqvp-postgres:
    image: postgres:16-alpine
    container_name: aqvp-postgres
    environment:
      POSTGRES_USER: aqvp
      POSTGRES_PASSWORD: aqvp
    ports:
      - "5432:5432"
    volumes:
      - aqvp-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aqvp"]
      interval: 5s
      timeout: 5s
      retries: 5

  aqvp-keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: aqvp-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      aqvp-postgres:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: aqvp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  aqvp-kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: aqvp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

volumes:
  aqvp-postgres-data:
