aqvp:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-very-long-secret-key-at-least-256-bits}

spring:
  application:
    name: admin-service
  profiles:
    active: dev
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${PORT:8084}
