spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_db
    username: aqvp
    password: aqvp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

server:
  port: 8084
