spring:
  datasource:
    url: ${ADMIN_DB_URL:jdbc:postgresql://localhost:5432/admin_db}
    username: ${ADMIN_DB_USERNAME:aqvp}
    password: ${ADMIN_DB_PASSWORD:aqvp}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

server:
  port: 8084
