spring:
  application:
    name: identity-service
  profiles:
    active: dev
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8081

aqvp:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-very-long-secret-key-at-least-256-bits}
      access-token-expiration-ms: 900000
      refresh-token-expiration-ms: 604800000
    api-client:
      header-client-id: X-Api-Client-Id
      header-client-secret: X-Api-Client-Secret

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
