spring:
  datasource:
    url: ${QUALIFICATION_DB_URL:jdbc:postgresql://localhost:5432/qualification_db}
    username: ${QUALIFICATION_DB_USERNAME:aqvp}
    password: ${QUALIFICATION_DB_PASSWORD:aqvp}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

server:
  port: 8082
