spring:
  datasource:
    url: ${VERIFICATION_DB_URL}
    username: ${VERIFICATION_DB_USERNAME}
    password: ${VERIFICATION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: verification
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: verification
    create-schemas: true

logging:
  level:
    root: WARN
    com.aqvp: INFO
