spring:
  datasource:
    url: ${VERIFICATION_DB_URL:jdbc:postgresql://localhost:5432/verification_db}
    username: ${VERIFICATION_DB_USERNAME:aqvp}
    password: ${VERIFICATION_DB_PASSWORD:aqvp}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

server:
  port: 8083
